package NoteInterfaceModule;


/**
* NoteInterfaceModule/NoteInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NoteInterface.idl
* samedi 13 novembre 2021 13 h 15 GMT+01:00
*/

public interface NoteInterfaceOperations 
{
  double getNote (short cin, String codeMatiere);
  void shutdown ();
} // interface NoteInterfaceOperations
