package NoteInterfaceModule;


/**
* NoteInterfaceModule/NoteInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NoteInterface.idl
* samedi 13 novembre 2021 13 h 15 GMT+01:00
*/

public interface NoteInterface extends NoteInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NoteInterface
